### ISSUE TITLE
render .rpdf is empty

### ISSUE THREAD

**Issue by alan-andrade** [lloeki/tilt-pdf#1]
I like where this gem is going. I tried to use it with Rails 4 and didn't work.

The final reponse is empty with a Content-Lenght of 1, a white space.

Have you had the same problem before ?

**Comment by lloeki** [comment]
I'm using this on Rails 3.2 projects currently. I'll be looking into this.

**Comment by lloeki** [comment]
I've set up scratch Rails 3.2.14 and Rails 4.0.2 projects, and both behave the same way, that is, correctly generate a PDF with expected content. IOW I can't replicate the issue.
