### ISSUE TITLE
Rails 4 require on Gemfile fails

### ISSUE THREAD

**Issue by alan-andrade** [lloeki/tilt-pdf#2]
If you require the gem on the Gemfile it will fail since ActionView is not loaded yet.

I had to require it in my config/application.rb ( I thought about doing it in a initializer but I find that an overkill for a `require` instruction )

**Comment by lloeki** [comment]
Did you use `gem 'tilt-pdf', require: 'tilt/pdf/rails'`?

**Comment by alan-andrade** [comment]
I did, I won't work like that.

**Comment by alan-andrade** [comment]
when I reported this I was in a hurry, let me setup an env. where I can show you how it fails.
